Adam/python/lab06
PdxCodeGuild/class_koi pull request #123
Opened 2022-03-23 14:42 UTC by AdamFraley

completed Lab06 and Version 2, added user input to determine the amount of Pick6 games

2022-03-23 23:01 UTC, knizzle requested changes
*`pick6()` function producing tickets of 7 numbers instead of 6

*re-look at how you're calculating balance and R.O.I. (hint: your 'earnings' are producing a negative number right now)

2022-03-26 01:51 UTC, knizzle approved these changes

2022-03-28 17:38 UTC, pjz987 commented
It looks like version 3 of lab 4 ended up on this branch.  Not a problem, just remember to keep an eye on your branches as you do work.

2022-03-28 17:38 UTC, pjz987 approved these changes

2022-03-28 17:38 UTC, merged