Shaine/python/lab08
PdxCodeGuild/class_koi pull request #124
Opened 2022-03-23 18:39 UTC by ShaineWarren

2022-03-25 17:40 UTC, knizzle requested changes
have another look at your 'check_digit' variable; code is returning 'invalid' when should be 'valid'

2022-03-25 17:51 UTC, knizzle commented
> have another look at your 'check_digit' variable; code is returning 'invalid' when should be 'valid'

@ShaineWarren sorry, nevermind! I misunderstood the instructions

2022-03-25 17:52 UTC, knizzle approved these changes

2022-03-28 17:46 UTC, pjz987 commented
it looks like this branch had some other things on it.  No worries, I cleaned things up.  Just be sure to pull down main and branch off that when you create branches in the future

2022-03-28 17:47 UTC, pjz987 approved these changes

2022-03-28 17:47 UTC, merged