Shaine/python/lab09
PdxCodeGuild/class_koi pull request #126
Opened 2022-03-23 21:05 UTC by ShaineWarren

2022-03-24 22:00 UTC, knizzle requested changes
Almost got it! Only thing that needs to change is we want the index of peaks and valleys, not the numbers themselves :)

2022-03-28 19:06 UTC, knizzle approved these changes

2022-03-28 19:13 UTC, pjz987 commented
Make sure you are 1) checking out main 2) pulling down main and 3) then making a branch off of main.  There is a bit of weirdness where you have old versions of files on your branches.  It's not hard for me to fix, but let me know if you have any questions about it so I can help you learn best git practices

2022-03-28 19:13 UTC, pjz987 approved these changes

2022-03-28 19:13 UTC, merged