Brandon/python/lab09
PdxCodeGuild/class_koi pull request #134
Opened 2022-03-23 23:13 UTC by bsarazin1

2022-03-28 19:27 UTC, pjz987 requested changes
I left a note for some changes I've requested.  Take a close look at the instructions, the 3 functions it asks of you and what they should do.

2022-03-28 19:27 UTC, pjz987 commented on code/Brandon/python/lab09/lab09.py
> +peaks_and_vallleys[1], peaks_and_vallleys[2] = peaks_and_vallleys[2], peaks_and_vallleys[1]
You're pretty close, but double check the instructions, you're asked to make 3 functions: `peaks`, `valleys` & `peaks_and_valleys`.  Also, your functions should return a list of indices.  Right now they're printing out information and returning `None`.   For the 3rd function `peaks_and_valleys`, you can reuse the other 2 functions as helpers.  I'm requested changes, let me know if you have any questions.

2022-04-19 23:24 UTC, knizzle approved these changes

2022-04-24 13:58 UTC, pjz987 approved these changes

2022-04-24 13:58 UTC, merged