added lab12.py and lab12.csv
PdxCodeGuild/class_koi pull request #161
Opened 2022-03-26 00:05 UTC by MattDWalsh

2022-03-28 23:03 UTC, knizzle requested changes
__init__.py

2022-03-29 16:37 UTC, MattDWalsh commented
@knizzle The module import has been fixed and should be ready to test!

2022-03-29 19:11 UTC, knizzle requested changes
@MattDWalsh Works really well!

However, when 'creating' another state, it asks for 'l' and 'd' entries, as well (was this intentional?).

Also, it might help to let the user know about its L and D options when updating a state before they get caught in the 'What would you like to update?' loop - but that's totally up to you.

Other than that, looks good!

2022-03-29 23:20 UTC, knizzle approved these changes

2022-03-31 21:28 UTC, pjz987 approved these changes

2022-03-31 21:28 UTC, merged