submitted lab13
PdxCodeGuild/class_koi pull request #205
Opened 2022-04-01 17:38 UTC by nathanBonilla

2022-04-01 18:01 UTC, knizzle requested changes
hey @nathanBonilla, one small thing: don't forget to add your 'print transactions' method to the list of commands. other than that, looks great!

2022-04-01 18:18 UTC, nathanBonilla commented
Thank you for the heads up Kelsey! I went ahead and made those changes as requested.

2022-04-01 21:23 UTC, knizzle approved these changes

2022-04-02 01:01 UTC, pjz987 approved these changes

2022-04-02 01:01 UTC, merged