Dan/python/lab13
PdxCodeGuild/class_koi pull request #229
Opened 2022-04-11 18:31 UTC by asddataking

2022-04-11 19:07 UTC, knizzle requested changes
Looks good, @asddataking! Just missing version 2 (don't forget to add the command to the while loop).

2022-04-25 18:16 UTC, knizzle requested changes
You're very close, @asddataking --

The 'print_transactions' method is not being called in the while loop (add an 'elif' command). 

You will actually be appending your 'transaction' list inside of your 'withdraw' and 'deposit' methods.

2022-04-25 21:10 UTC, knizzle approved these changes

2022-05-02 19:16 UTC, pjz987 approved these changes

2022-05-02 19:16 UTC, merged