lab05
PdxCodeGuild/class_koi pull request #371
Opened 2022-05-20 19:51 UTC by ShaineWarren

2022-05-20 21:36 UTC, knizzle requested changes
Having trouble with the delete function -- items getting pushed down the list.

For example:

- [ ] first
[x] ~~second~~
- [ ] third
[x] ~~fourth~~
- [ ] fifth

if I delete the third (incompleted) item, I get this:

- [ ] first
[x] ~~second~~
- [ ] fourth
[x] ~~fifth~~

2022-05-24 17:11 UTC, knizzle requested changes
not sure what happened lol, but now it's adding 'completed' tasks when I delete?

one
~~two~~
three
~~four~~
five

and after deleting 'three':

one
~~two~~
~~four~~
~~five~~

just wanted to add: this is one of the best-looking to-do apps I've ever seen!

2022-05-24 22:27 UTC, knizzle approved these changes
FANTASTIC job, @ShaineWarren !

2022-06-08 20:41 UTC, pjz987 approved these changes

2022-06-08 20:41 UTC, merged