lab04.py
PdxCodeGuild/class_koi pull request #48
Opened 2022-03-16 19:26 UTC by logandouglass

2022-03-18 18:08 UTC, lisab1993 requested changes
Version 1: 10 returns '10' instead of 'ten', but the other numbers are correct. Version 2: same issue as version 1; 110 returns a key error (this happens in all of the hundreds); everything else is done and good to go.

2022-03-22 22:35 UTC, knizzle approved these changes

2022-03-24 19:04 UTC, pjz987 commented
it looks like lab 05 ended up on this one too.  going to go ahead and merge.  just something to keep an eye on

2022-03-24 19:14 UTC, pjz987 approved these changes

2022-03-24 19:14 UTC, merged