Adam/python/lab04
PdxCodeGuild/class_koi pull request #66
Opened 2022-03-17 19:13 UTC by AdamFraley

Lab 04: Number to Phrase with Version 2 added

2022-03-18 18:36 UTC, lisab1993 requested changes
Version 1: done. Version 2: 110-119 returns results like 'one-hundred -four', and this happens with the other hundred numbers; everything else looks great!

2022-03-18 19:13 UTC, AdamFraley commented
@lisab1993 I made the changes as requested

2022-03-21 23:11 UTC, IronWill12 commented
Corrections work, good job.

2022-03-24 18:59 UTC, pjz987 approved these changes

2022-03-24 18:59 UTC, merged