Brandon/python/lab06
PdxCodeGuild/class_koi pull request #75
Opened 2022-03-17 23:11 UTC by bsarazin1

Lab06

2022-03-21 18:51 UTC, bsarazin1 commented
I reloaded lab06.py hopefully it updated here.

2022-03-28 17:10 UTC, knizzle requested changes
re-look at 'winnings' -- looks like I am winning $1 billion while spending only  $200k. 

remember to calculate ROI, as well.

2022-03-30 22:50 UTC, knizzle approved these changes

2022-03-31 21:17 UTC, pjz987 approved these changes

2022-03-31 21:17 UTC, merged