submitted lab06
PdxCodeGuild/class_koi pull request #82
Opened 2022-03-18 19:24 UTC by nathanBonilla

2022-03-23 21:05 UTC, knizzle reviewed
@pjz987  Please review.

2022-03-23 21:37 UTC, knizzle requested changes
Re-look at 'matches'; should only be a 'match' if in same index, as well.

Right now looks like:
winning ticket = [92, 26, 88, 62, 69, 38], my ticket = [94, 92, 12, 80, 38, 66]
matches = 2 --> should be 0

2022-03-23 21:52 UTC, nathanBonilla commented
Hi Kelsey,
From lines 46 - 49 I implemented a "Orders Strictly Matters" section where the matches are only counted when the indexes of both tickets are the same.  The lab was ambiguous on this, so I implemented multiple solutions.  I should have written it out in separate functions.  Please let me know if that function will suffice.

2022-03-24 23:21 UTC, pjz987 approved these changes

2022-03-24 23:21 UTC, merged